doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            domaineEtude: App\MesEnumType\DomaineEtudeType
            niveauFormation: App\MesEnumType\NiveauFormationType
            typeContrat: App\MesEnumType\TypeContratType
            domaineActivite: App\MesEnumType\DomaineActiviteType
            typeAbonnement: App\MesEnumType\TypeAbonnementType
            localites: App\MesEnumType\LocalitesType
            motifs: App\MesEnumType\MotifsType
            anneeExperience: App\MesEnumType\AnneeExperienceType
            statut: App\MesEnumType\StatutType
            niveauDePoste: App\MesEnumType\NiveauDePosteType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
