vich_uploader:
    db_driver: orm

    mappings:
        diplomes_files:
            uri_prefix: /diplomes
            upload_destination: '%kernel.project_dir%/public/diplomes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        cv_files:
            uri_prefix: /repertoirecv
            upload_destination: '%kernel.project_dir%/public/repertoirecv'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        image_user:
            uri_prefix: /image
            upload_destination: '%kernel.project_dir%/public/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
